### ISSUE TITLE
Install instructions needed

### ISSUE THREAD

**Issue by sofar** [est31/minetest-flatpak#1]
It would be good to have a readme.md or similar with instructions, explaining the steps needed to install the org.freedesktop.Platform runtime if needed, and how to run the right commands.

**Comment by sofar** [comment]
so far I've cobbled up:

```
curl -L -O https://github.com/est31/minetest-flatpak/releases/download/v1.0/Minetest-0.4.14.flatpak
flatpak install --runtime gnome org.freedesktop.Platform 1.4
flatpak install --bundle Minetest-0.4.14.flatpak
```

**Comment by est31** [comment]
I've had install instructions on the [forum](https://forum.minetest.net/viewtopic.php?f=42&t=15336), but adding it to github as well is probably a good idea.
